if(-not (test-path "$PSScriptRoot\xivdata")){mkdir "$PSScriptRoot\xivdata"}
Invoke-WebRequest "https://raw.githubusercontent.com/xivapi/ffxiv-datamining/master/csv/Item.csv" -OutFile "$PSScriptRoot\xivdata\item.csv"
$data = import-csv "$PSScriptRoot\xivdata\item.csv"
$itemsToFind=(
"Acidic Secretions",
"Aldgoat Leather",
"Aldgoat Skin",
"Alumen",
"Animal Hide",
"Animal Skin",
"Approved Grade 4 Skybuilders’ Alumen",
"Approved Grade 4 Skybuilders’ Cotton Boll",
"Approved Grade 4 Skybuilders’ Electrum Ore",
"Approved Grade 4 Skybuilders’ Gold Sand",
"Approved Grade 4 Skybuilders’ Hemp",
"Approved Grade 4 Skybuilders’ Iron Ore",
"Approved Grade 4 Skybuilders’ Iron Sand",
"Approved Grade 4 Skybuilders’ Mahogany Log",
"Approved Grade 4 Skybuilders’ Mistletoe",
"Approved Grade 4 Skybuilders’ Mythrite Sand",
"Approved Grade 4 Skybuilders’ Ore",
"Approved Grade 4 Skybuilders’ Ragstone",
"Approved Grade 4 Skybuilders’ Rock Salt",
"Approved Grade 4 Skybuilders’ Sesame",
"Approved Grade 4 Skybuilders’ Spring Water",
"Approved Grade 4 Skybuilders’ Spruce Log",
"Approved Grade 4 Skybuilders’ Switch",
"Approved Grade 4 Skybuilders’ Tea Leaves",
"Approved Grade 4 Skybuilders’ Toad",
"Approved Grade 4 Skybuilders’ Vine",
"Ash Log",
"Ash Lumber",
"Atrociraptor Leather",
"Bear Fat",
"Beast Sinew",
"Beehive Chip",
"Beeswax",
"Bluespirit Tile",
"Brass Ingot",
"Bronze Ingot",
"Buffalo Milk",
"Cinnamon",
"Cloud Mica Whetstone",
"Cobalt Ore",
"Coffee Beans",
"Copper Ore",
"Cotton Yarn",
"Cubus Flesh",
"Dark Chestnut Lumber",
"Dew Thread",
"Diremite Web",
"Effervescent Water",
"Electrum Ore",
"Elm Log",
"Elm Lumber",
"Faerie Apple",
"Garden Beet Sugar",
"Garlean Garlic",
"Hard Leather",
"Hardsilver Nugget",
"Hempen Yarn",
"Holy Basil",
"Iron Ingot",
"Iron Ore",
"Iron Plate",
"Iron Rings",
"Iron Rivets",
"Kudzu Cloth",
"Kudzu Root",
"Latex",
"Light Gerbera",
"Manasilver Nugget",
"Maple Log",
"Maple Sap",
"Maple Syrup",
"Mineral Water",
"Mistletoe",
"Muddy Water",
"Mudstone",
"Mythril Ingot",
"Oroshigane Ingot",
"Peiste Skin",
"Pine Lumber",
"Pixie Cotton",
"Pixie Floss",
"Pixie Plums",
"Potters Clay",
"Ragstone",
"Ramie Thread",
"Rock Salt",
"Ruby Tomato",
"Rue",
"Silver Ore",
"Slate Whetstone",
"Sour Cream",
"Star Ruby",
"Straw",
"Sun Lemon",
"Sunset Wheat Flour",
"Tiger Leather",
"Tin Ore",
"Titanbronze Ingot",
"Titanbronze Nugget",
"Titanium Nugget",
"Twinthread",
"Underground Spring Water",
"White Ash Lumber",
"Wild Onion",
"Woolen Yarn",
"Yew Log",
"Zinc Ore"
)

$found = @{}
foreach($item in $data){
    if ($itemsToFind -contains $item.9){
        $found.add($item.9,$item.key)
    }
}

$found.GetEnumerator() | Select-Object -Property Key,Value |Export-Csv -NoTypeInformation -Path "$PSScriptRoot\xivdata\xivItemIds.csv"